### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by winterstein** [wchern/Twit4Java#1]
Hello @wchern 

I saw your JTwitter project -- Could I suggest you alter the name slightly to avoid confusion with my  project (https://github.com/winterstein/JTwitter)? Entirely up to you of course. A different name (e.g. JavaTwitter) would likely be good for both projects by avoiding confusion. 

Drop me a line if you want to talk,
- Daniel

**Comment by chern** [comment]
Hey @winterstein,

Thanks for contacting me about the potential naming confusion. I've changed it to TwitterForJava to avoid potential confusion with your project. A friend ( @nishand17 ) and I are simply working on this as a school project for fun, so the name isn't a big deal.

– William

**Comment by winterstein** [comment]
Thanks @wchern :)
